included: # paths to include during linting. `--path` is ignored if present.
  - Routes
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - variable_name
  - conditional_binding_cascade
variable_name:
  excluded: # excluded via string array
    - id
    - db
